### ISSUE TITLE
Course not re-rendering

### ISSUE THREAD

**Issue by KatherineCox** [ottrproject/OTTR_Template#18]
I just merged #16 into OTTR_Template, but the website doesn't appear to have been re-rendered. Looking at the time the files in `docs` were last modified, it looks like the tocless render worked but the "normal" render did not.

In the [Actions log](https://github.com/ottrproject/OTTR_Template/actions/runs/15113475123/job/42478196195#step:4:538), I see this, which seems likely to be the problem?

```
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: 
remote: - Changes must be made through a pull request.        
To https://github.com/ottrproject/OTTR_Template
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/ottrproject/OTTR_Template'
No changes to push
```

**Comment by avahoffman** [comment]
I think this might have to do with the branch being protected. Not sure why this hasn't been an issue before, but might have to do with the unified ottr-preview action.

Maybe we allow the github actions bot to bypass branch protection rules? Could that backfire for safety reasons?

>Allow specified actors to bypass required pull requests
>Specify people, teams, or apps who are allowed to bypass required pull requests.

**Comment by kweav** [comment]
Hoping that PR #23 will fix this

**Comment by kweav** [comment]
@avahoffman @KatherineCox I think this issue should be resolved after we merged PR #23. You'll hopefully find a relevant sync in your AnVIL/C-Moor/etc repos shortly, but please let me know if not.

**Comment by KatherineCox** [comment]
@kweav Do you think it matters that I (the person merging the PR) only have "write" permission on this repo (so, lower than the usual ottr maintainers)? Or was is just a problem with the robot?

I don't know enough to make a guess about that, so I'm happy to trust your judgement here. If you think there's a chance it matters who merged the PR, I can try merging a new PR (just adding a newline) to confirm it renders correctly when I do it. But if you're reasonably sure you've handled the problem, then yep, you can close this issue.

**Comment by KatherineCox** [comment]
@kweav okay, sounds likely that you fixed it if you were seeing (and successfully resolved) the same problem in other repos. Let's give it a sanity check just to be sure: #26

**Comment by kweav** [comment]
@KatherineCox I can't tell if your change got incorporated.... does it look like it to you?

**Comment by KatherineCox** [comment]
Yeah, #26 was just adding a newline so it shouldn't have any visible change, but the html files should still get rerendered, which you can see from the date they were last updated.

Two visible changes I *would* expect to see though, if the website successfully rerendered:
- the date on the first page should change from April to June
- my css changes from #16, which would, among other things, add underlines to the links.

**Comment by KatherineCox** [comment]
Sounds good, thanks everyone for looking into this!

I submitted another PR #33 to check whether the rerendering works with my newly upgraded permissions. I'm not actually sure whether or not my permission level is the problem, that was just a guess from the error message (which is complaining about branch protection), so let's double check before sending you all off down the wrong rabbit trail.

**Comment by KatherineCox** [comment]
Same problem when merging #33 (html files did not update), so I think it's not my personal permission level that matters.

Still seeing the same error (`GH006: Protected branch update failed for refs/heads/main`)

**Comment by avahoffman** [comment]
I'm not exactly sure why this is happening now, but the issue can be bypassed by removing the branch protections for `main`. I think one solution could be to give the jhurobot (if they are being signed in as part of the workflow render-all) permission to bypass branch rules.

**Comment by avahoffman** [comment]
Seems to be working when testing here https://github.com/ottrproject/OTTR_Template/actions/runs/15640001316. @kweav want to merge and see if it resolves the issue? If not we can revert and go back to the drawing board.

**Comment by avahoffman** [comment]
@cansavvy I think we have a solution - permissions weren't being passed to ottr-preview checkout when  preview == false. 

I like the idea of deploying Pages from something like `published/docs` instead of `main/docs` so that main stays clean. However it might be weird for the branch serving to a public website to not have protections. We'd have the same issue over there as well.

**Comment by kweav** [comment]
@avahoffman is this issue good to close?
